### PR TITLE
Fix copyright date

### LINKED ISSUE #254: Bugfix: copyright on documentation needs updated to 2024
**Describe the bug**
Wrong date on documentation copyright statement

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by j-emberton**
Change date to 2024

# Description

Changed date in conf.py.

Copyright should reflect when the last edits to the documentation were made.

Fixes #254 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [ ] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [ ] All tests pass: `$ poetry run pytest`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by davidorme** [comment]
Probably makes sense to make this dynamic to get the current year. I'm also not sure who we should put as copyright holders. We don't want a long list, but does it make sense to use `pyrealm contributors` or similar.

**Comment by j-emberton** [comment]
I'm not really sufficiently up to speed on IP to say definitively, but perhaps an alternative license statement to a copyright declaration might be appropriate. I asked ChatGPT about this and it came up with the following

`
Creative Commons Licenses (CC):

CC BY (Attribution): Allows others to distribute, remix, adapt, and build upon the work, even commercially, as long as they credit the original creation.
CC BY-SA (Attribution-ShareAlike): Similar to CC BY but requires derivatives to be licensed under identical terms.
CC BY-ND (Attribution-NoDerivs): Allows for redistribution, commercial and non-commercial, as long as it is passed along unchanged and in whole, with credit to the original creation.
CC BY-NC (Attribution-NonCommercial): Allows others to remix, adapt, and build upon the work non-commercially, and although their new works must also acknowledge the original creator and be non-commercial, they don’t have to license their derivative works on the same terms.
CC0 (Public Domain Dedication): Waives all copyrights and related rights to the extent possible, placing the work in the public domain.
GNU Free Documentation License (GFDL):

This is a copyleft license for free documentation, designed by the Free Software Foundation (FSF) for the GNU Project. It allows the documentation to be freely used, modified, and distributed, with the requirement that all copies and derivatives are also licensed under the GFDL.
Open Documentation License (ODL):

Similar to the GNU FDL, this license allows for the free use, copying, distribution, and modification of the documentation. However, it is less commonly used compared to CC and GFDL.
To apply one of these licenses to your Python package documentation, you typically include a license file (e.g., LICENSE or LICENSE.txt) in the root of your documentation repository or directory, specifying the terms under which the documentation is licensed. You might also include a brief license notice in the documentation itself, usually in a preface or footer, to clearly indicate the licensing terms to users.
`

**Comment by j-emberton** [comment]
This is the Numpy approach:

© Copyright 2008-2024, NumPy Developers.

**Comment by davidorme** [comment]
> This is the Numpy approach:
> 
> © Copyright 2008-2024, NumPy Developers.

Yeah - I think we should do this.

**Comment by j-emberton** [comment]
OK, I hope this is good to go

**Pull request merged**
