### PR TITLE
Fixing missing attribute docstrings in `core.calendar`

### LINKED ISSUE #164: Missing attribute docstrings in `core.calendar`
**Describe the bug**
There are no attribute docstrings for `core.calendar` objects so the API docs are useless.

**Expected behavior**
Should have properly documented attributes.

Depends on the SPLASH PR in #69

### PR DESCRIPTION
**Pull request by davidorme**
# Description

This PR:

* Adds attribute docstrings to `Calendar` and `CalendarDay`
* Updates the docstrings throughout the module.
* Adds a custom and more compact `__repr__` for both dataclasses.
Fixes #164

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by surbhigoel77 — COMMENTED** [review]
Looks good to me.

**Comment by davidorme** [comment]
Hi @surbhigoel77 - can you re-review and approve? You've added a "comment review" but I need an "approving review" to merge it 😄

**Review by surbhigoel77 — APPROVED** [review]
LGTM.

**Comment by surbhigoel77** [comment]
> Hi @surbhigoel77 - can you re-review and approve? You've added a "comment review" but I need an "approving review" to merge it 😄

Corrected. :)

**Pull request merged**
