### PR TITLE
Remove support for Python 3.9

### LINKED ISSUE #196: Remove support for Python 3.9
**Is your feature request related to a problem? Please describe.**

As discussed, drop Python 3.9 in preparation for release 1.0.0 and add `pyupgrade` to the `pre-commit` tools to automatically update the code. Some places will need manual updates - versions used in GitHub action workflows for example.

The changes are likely to be very similar to this PR:

https://github.com/ImperialCollegeLondon/virtual_ecosystem/pull/356

### PR DESCRIPTION
**Pull request by davidorme**
# Description

This PR:

* adds `pyupgrade` to the `pre-commit` toolchain and sets `py310-plus`,
* uses `pre-commit run --all` to apply automatic upgrading to the codebase,
* removes now redundant imports of `Union, Optional, Type`,
* updates the GitHub and RTD configurations to drop 3.9 and use Python 3.11 where a single env is used,
* updates the package docs and `poetry` to drop Python 3.9

Fixes #196

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by davidorme** [comment]
Awaiting fix of broken RTD environment in #204 to double check that the new setup without 3.9 builds on RTD.

**Review by MarionBWeinzierl — COMMENTED** [review]
This should be ok, but maybe @surbhigoel77 has time to have a look over it, too?

**Comment by davidorme** [comment]
Yup - that sounds good. I'll start putting together a release branch soon.

**Review by surbhigoel77 — APPROVED** [review]
@davidorme LGTM.

**Pull request merged**
