### PR TITLE
Updated module import in pmodel unit tests

### LINKED ISSUE #205: Streamline the import of modules in tests
In current codebase, the import of modules in test files is inconsistent and needs to be modified in a way that the required modules are imported within the testcases instead of importing all modules at once, so that failure of one import does not impact other testcases.

### PR DESCRIPTION
**Pull request by surbhigoel77**
# Description

Updating the import of modules in test files, by moving specific imports within tests.

Fixes #205 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by davidorme** [comment]
@surbhigoel77 There is a whole host of `numpy` related references that don't seem to play nicely with the `intersphinx` plugin that allows `pyrealm` to point to docs in other packages. There's a section in the `sphinx` `conf.py` that is basically a big collection of us telling `sphinx` to shut up about things like this. 

I've added `np.bool_`, which sorts this out but I may be missing something that allows us to make this work properly.

https://github.com/ImperialCollegeLondon/pyrealm/blob/423f08be155ab8976ca337b1354d2f1ed8272d29/docs/source/conf.py#L88-L140

**Comment by surbhigoel77** [comment]
> @surbhigoel77 There is a whole host of `numpy` related references that don't seem to play nicely with the `intersphinx` plugin that allows `pyrealm` to point to docs in other packages. There's a section in the `sphinx` `conf.py` that is basically a big collection of us telling `sphinx` to shut up about things like this.
> 
> I've added `np.bool_`, which sorts this out but I may be missing something that allows us to make this work properly.
> 
> https://github.com/ImperialCollegeLondon/pyrealm/blob/423f08be155ab8976ca337b1354d2f1ed8272d29/docs/source/conf.py#L88-L140

Thanks @davidorme.

**Comment by surbhigoel77** [comment]
Screenshot 2024-06-20 at 19 56 37


@davidorme I tried the updated docs config, and I get this error around numpy where docstrings expects `np.float64(1.12536)` as output but actual output is `1.12536`, for multiple files on running pytest.

**Comment by davidorme** [comment]
@surbhigoel77 - That's odd as it passes on the actions. Maybe you need to `poetry update`? @j-emberton made some changes in the packages for the `numpy` 2.0 update, could be they are out of sync?

**Comment by j-emberton** [comment]
The code with the error @surbhigoel77 highlights is one of the fixes I made and is definitely merged into `develop`. Worth making sure that you are completely up to date with develop and run poetry update to make sure all the latest dependencies are in place as @davidorme suggests.

Screenshot 2024-06-21 at 09 58 19

**Comment by surbhigoel77** [comment]
Thanks @davidorme  and @j-emberton. I updated both my local develop branch and poetry, and it works fine.

**Review by davidorme — APPROVED** [review]
LGTM

**Pull request merged**
